kras/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from compras import views as compras_views
from compras_terceiros import views as compras_terceiros_views
from vendas import views as vendas_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path("compras/relatorio/", compras_views.compra),
    path("compras_terceiros/relatorio/", compras_terceiros_views.compra),
    path("vendas/relatorio/", vendas_views.vendas)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Kras Engenharia'
admin.site.index_title  = 'Sistema'
admin.site.site_title = "Kras Engenharia"

compras_terceiros/models.py
from django.db import models
from cadastro import models as cadastro_models


# Create your models here.
class ComprasTeceiros(models.Model):
    PC_CHOICES = (
        ('env', "Enviado"),
        ('emit', "Emitido"),
        ('nemit', "Não Emitido"),
    )
    PAGAMENTO_CHOICES = (
        ('pg', "Pago"),
        ('npg', "Não Pago"),
    )
    HEPERCENT_CHOICES = (
        ('50', "50%"),
        ('75', "75%"),
        ('100', "100%"),
    )
    DESPESA_CHOICES = (
        ('despesa',"Despesa"),
        ('servico', "Serviço"),
    )
    CONDICAO_CHOICES = (
        ('28ddl', '28ddl'),
        ('45ddl', '45ddl'),
        ('variavel', 'Variável'),
    )
    METODO_PAGAMENTO_CHOICES = (
        ('boleto', 'Boleto'),
        ('transferencia', 'Transferência Bancária')
    )
    numero_os = models.PositiveIntegerField(default=0)
    data = models.DateField(null=True, blank=True)
    condicao_de_pagamento = models.CharField(max_length=100, choices=CONDICAO_CHOICES, null=True, blank=True)
    metodo_de_pagamento = models.CharField(max_length=100, choices=METODO_PAGAMENTO_CHOICES, null=True, blank=True)
    projeto = models.CharField(max_length=100, null=True, blank=True)
    pedido_compra = models.CharField(max_length=100, choices=PC_CHOICES, null=True, blank=True)
    pagamento_compra = models.CharField(max_length=100, choices=PAGAMENTO_CHOICES,null=True, blank=True)
    notafiscal = models.CharField(max_length=200, null=True, blank=True)
    inspetor = models.ForeignKey(cadastro_models.Colaborador, on_delete=models.SET_NULL, null=True, blank=True)
    observacoes = models.TextField(null=True, blank=True)
    fornecedor = models.ForeignKey(cadastro_models.Fornecedor, on_delete=models.SET_NULL, null=True, blank=True)
    class Meta:
        verbose_name = "Compra de Terceirizada"
        verbose_name_plural = "Compras de Terceiros"


class ItemCompras(models.Model):
    HEPERCENT_CHOICES = (
        ('50', "50%"),
        ('75', "75%"),
        ('100', "100%"),
    )
    compra = models.ForeignKey(ComprasTeceiros, on_delete=models.CASCADE)
    servico = models.ForeignKey(cadastro_models.Servico, on_delete=models.CASCADE, null=True, blank=True)
    data = models.DateField(null=True, blank=True)
    horas_trabalhadas = models.FloatField(null=True, blank=True)
    horas_extras = models.FloatField(null=True, blank=True)
    horas_extras_percentuais = models.CharField(max_length=100, choices=HEPERCENT_CHOICES, null=True, blank=True)
    anormalidade = models.FloatField(null=True, blank=True)
    reembolso = models.FloatField(null=True, blank=True)
    qtd = models.FloatField(null=True, blank=True)
    preco = models.FloatField(null=True, blank=True)
    class Meta:
        verbose_name = "Item da Compra"
        verbose_name_plural = "Itens da Compra"

class DespesasCompras(models.Model):
    compra = models.ForeignKey(ComprasTeceiros, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=100, null=True, blank=True)
    reembolso = models.FloatField(null=True, blank=True)
    preco = models.FloatField(null=True, blank=True)

compras_terceiros/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import ComprasTeceiros, ItemCompras, DespesasCompras
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.

@login_required(login_url="/admin")
def compra(request):
    compra_id = request.GET.get("compra")
    try:
        compra = ComprasTeceiros.objects.get(id=compra_id)
    except:
        return HttpResponse("400 - Bad Request. Compra inexistente.", status=400)
    compra_itens = ItemCompras.objects.filter(compra=compra)
    compra_despesas = DespesasCompras.objects.filter(compra=compra)
    template = loader.get_template("relatorio.html")
    total = 0
    total_despesas = 0
    for item in compra_itens:
        try: total = total + item.qtd * item.preco
        except: print(item)
    for item in compra_despesas:
        total_despesas = total_despesas 
    context = {
        "compra": compra,
        "itens": compra_itens,
        "despesa": compra_despesas,
        "total": "R$ {:.2f}".format(total),
        "total_despesas": "R$ {:.2f}".format(total_despesas)
    }
    return HttpResponse(template.render(context, request))

    #
    # + item.preco

compras_terceiros/templates/relatorio.html
{% load static %}
<html>
    <head>
        <title>Compra {{compra.id}}</title>
        <style type="text/css">
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap');
            body{
                font-family: 'Open Sans', sans-serif;
                height: 842px;
                width: 720px;
                /* to centre page on screen*/
                margin-left: auto;
                margin-right: auto;
                color-adjust:exact;
            }
            .header{
                width: 100%;
            }
            th, td{
              border: 1px solid #ccc;
            }
            .header .in-td{
                vertical-align: middle;
                margin: 0;
                text-align: center;
                border-collapse: collapse;
            }
            .header .in-td img{
                max-width: 100%;
            }
            .header td h4{
                text-decoration: none;
                font-weight: normal;
                margin-top: -10px;
                padding: 0;
            }

            .info-compra{
                font-size: 10pt;
                width: 100%;
                border-collapse: collapse;
            }
            .info-compra td{
                width: 50%;
                padding: 2px;
                border: 1px solid #000 !important;
            }
            .info-compra .fundo{
                background-color: #ccc;
                font-weight: bold;
            }

            .info-partes{
                margin-top: 10px;
                width: 100%;
                font-size: 10pt;
            }

            .no-border td{
                border: none !important;
            }
            .blue{
                background-color: #001f5e;
                color: #fff;
                font-weight: bold;
            }
            .color-blue{
                color: #001f5e;
            }

            .info-produtos{
                margin-top: 30px;
                width: 100%;
                font-size: 10pt;
                border-collapse: collapse;
                
            }
            .info-produtos th{
                background-color: #ccc;
                font-weight: bold;
                border: 1px solid #fff;
            }
            .footer{
                width: 100%;
                border: none;
            }
        </style>
    </head>
    <body>
        <div>
            <table class="header">
                <tr>
                    <td class="in-td" style="width: 20%;"><img src="{%static 'kras_logo.png'%}">
                    <td class="in-td" style="width: 30%;"><h3>PEDIDO DE COMPRA</h3><h4>PURCHASE ORDER</h4></td>
                    <td class="in-td">
                        <table class="info-compra">
                            <tr>
                                <td class="fundo">Código</td>
                                <td>{{compra.id}}</td>
                            </tr>
                            <tr>
                                <td class="fundo">Número OS</td>
                                <td>{{compra.numero_os}}</td>
                            </tr>
                            <tr>
                                <td class="fundo">Projeto</td>
                                <td>{{compra.projeto}}</td>
                            </tr>
                            <tr>
                                <td class="fundo">Status</td>
                                <td>{{compra.get_pagamento_compra_display}}</td>
                            </tr>
                            <tr>
                                <td class="fundo">Inspetor</td>
                                <td>{{compra.inspetor}}</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>

            <table class="info-partes">
                <tr class="no-border">
                    <td style="width: 40%;">De / From:</td>
                    <td>Para / To:</td>
                </tr>
                <tr class="blue">
                    <td>Kras Engenharia, Consultoria e Inspeção Ltda</td>
                    <td>{{compra.fornecedor.nome}}</td>
                </tr>
                <tr>
                    <td class="color-blue">
                        Rua Clóvis Soares, 200 - Torre Japão, Sala 201 -  Alvinópolis<br>
                        CEP: 12942-560 - Atibaia-SP<br>
                        CNPJ: 21.592.185/0001-40<br>
                        Telefone: (011) 4260-0138<br>
                        E-mail: kras@krasengenharia.com.br<br>
                        Site: www.krasinspecao.com.br
                    </td>
                    <td>
                        <table class="info-compra">
                            <tr>
                                <td class="fundo">Código</td>
                                <td>{{compra.fornecedor.id}}</td>
                            </tr>
                            <tr>
                                <td class="fundo">Email</td>
                                <td>{{compra.fornecedor.email}}</td>
                            </tr>
                            <tr>
                                <td class="fundo">CNPJ</td>
                                <td>{{compra.fornecedor.cnpj}}</td>
                            </tr>

                            <tr>
                                <td class="fundo">Telefone</td>
                                <td>{{compra.fornecedor.telefone}}</td>
                            </tr>
                            <tr>
                                <td class="fundo">Endereço</td>
                                <td>{{compra.fornecedor.rua}} {{compra.fornecedor.numero}} - {{compra.fornecedor.cidade}} - {{compra.fornecedor.estado}}</td>
                            </tr>

                        </table>
                    </td>
                </tr>
            </table>

            <table class="info-produtos">
                <tr class="no-border">
                    <th>#</th>
                    <th>Serviço</th>
                    <th>Data</th>
                    <th>HT</th>
                    <th>QTD</th>
                    <th>HE</th>
                    <th>%</th>
                    <th>AN</th>
                    <th>Reembolso</th>
                    <th>Preço</th>
                </tr>
                {% for item in itens %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.servico}}</td>
                    <td>{{item.data}}</td>
                    <td>{{item.horas_trabalhadas}}</td>
                    <td>{{item.qtd}}</td>
                    <td>{{item.horas_extras}}</td>
                    <td>{{item.get_horas_extras_percentuais_display}}</td>
                    <td>{{item.anormalidade}}</td>
                    <td>{{item.reembolso}}</td>
                    <td>{{item.preco}}</td>
                </tr>
                {% endfor %}
            </table>

            <table class="info-produtos">
                <tr class="no-border">
                    <th>#</th>
                    <th>Despesa</th>
                    <th>Reembolso</th>
                    <th>Preço</th>
                </tr>
                {% for item in despesa %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.descricao}}</td>
                    <td>{{item.reembolso}}</td>
                    <td>{{item.preco}}</td>
                </tr>
                {% endfor %}
            </table>

            <table class="info-produtos">
                <tr>
                    <th>Observações</th>
                </tr>
                <tr>
                    <td style="min-height: 300px;">
                        {{compra.observacoes}}
                    </td>
                </tr>
            </table>

            <table class="footer">
                <tr>
                    <td style="width: 50%;  border: 0;">
                        <table class="info-produtos">
                            <tr>
                                <th colspan="2">Legenda</th>
                            </tr>
                            <tr>
                                <th>PC</th>
                                <td>Pedido Geral de Compra</td>
                            </tr>
                            <tr>
                                <th>IT</th>
                                <td>Item</td>
                            </tr>
                        </table>

                        <table class="info-produtos">
                            <tr>
                                <td class="blue">Condição de pagamento</td>
                                <td>{{compra.get_condicao_de_pagamento_display}}</td>
                            </tr>
                            <tr>
                                <td class="blue">Método de pagamento</td>
                                <td>{{compra.get_metodo_de_pagamento_display}}</td>
                            </tr>
                        </table>
                    </td>
                    <td style="border: 0;padding-left: 50px;">
                        <table class="info-produtos">
                            <tr>
                                <th>DESPESAS</th>
                                <td>{{total_despesas}}</td>
                            </tr>
                            <tr>
                                <td class="blue" style="text-align: center;">TOTAL</td>
                                <td>{{total}}</td>
                            </tr>
                        </table>
                    </td>
                </div>
            </table>

        </div>
    </body>
</html>